CIP.Web/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CIP.Web.Controllers
{
    public class AuthController : BaseController
    {
        public ActionResult Index()
        {
            Session.Clear();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string username, string password)
        {
            var objUsuario = Contexto.Usuarios
                .FirstOrDefault(x => x.Usuario == username && x.Contraseña == password);

            if (objUsuario != null)
            {
                if ((bool)objUsuario.Bloqueado)
                {
                    ViewBag.MensajeLogin = "El usuario se encuentra bloqueado.";
                    return View();
                }

                Session["IdUsuario"] = objUsuario.IdUsuario;
                Session["Rol"] = objUsuario.Roles.Nombre;
                Session["Nombre"] = $"{objUsuario.Datos}";

                return RedirectToAction("Index", "Home");
            }

            ViewBag.MensajeLogin = "El usuario o contraseña son incorrectos.";
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

CIP.Web/Controllers/EspecialidadController.cs
using CIP.Models.Contexto;
using CIP.Models.Helpers;
using CIP.Web.Filters;
using CIP.Web.Helpers;
using CIP.Web.Models.Especialidad;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CIP.Web.Controllers
{
    public class EspecialidadController : BaseController
    {
        [RolAuthFilter(ConstanHelpers.Rol.Administrador)]
        public ActionResult Index()
        {
            var viewModel = new EspecialidadIndexViewModel();

            var lista = Contexto.Especialidades.ToList();
            //.Where(x => x.TipoPreguntaId == ConstanHelpers.TipoPregunta.PreguntaFrecuente)
            //.ToList(); 

            viewModel.ListPreguntas = lista;

            return View(viewModel);
        }

        [RolAuthFilter(ConstanHelpers.Rol.Administrador)]
        public ActionResult Detail(int Idespecialidad)
        {
            var viewModel = new EspecialidadDetailViewModel();

            viewModel.IdEspecialidad = Idespecialidad;
            // llave primaria de una columna
            viewModel.EspecialidadesDetail = Contexto.Especialidades.Find(Idespecialidad);

            // llave primaria compleja de mas de una columna
            //Contexto.ConsultaLegal.FirstOrDefault(x => x.ConsultaLegalId == 10 &&
            //        x.Estado == "XYZ" && x.TemaId == 9);

            return View(viewModel);
        }

        [RolAuthFilter(ConstanHelpers.Rol.Administrador)]
        public ActionResult Delete(int Idespecialidad)
        {
            try
            {
                var objEspecialidad = Contexto.Especialidades
                    .FirstOrDefault(x => x.IdEspecialidad == Idespecialidad);// &&
                                                                         // x.TipoPreguntaId == ConstantHelpers.TipoPregunta.PreguntaFrecuente);

                if (objEspecialidad == null)
                {
                    TempData["MensajeEspecialidad"] = "El registro no existe en BD.";
                    return RedirectToAction("Index");
                }

                Contexto.Especialidades.Remove(objEspecialidad);
                Contexto.SaveChanges();
                TempData["MensajeEspecialidad"] = "El registro fue eliminado exitosamente.";
            }
            catch (Exception ex)
            {
                TempData["MensajeEspecialidad"] = "Ocurrio un error, contacte con el administrador";
            }

            return RedirectToAction("Index");
        }

        [RolAuthFilter(ConstanHelpers.Rol.Administrador)]
        public ActionResult AddEdit(int? Idespecialidad)
        {
            var viewModel = new EspecialidadAddEditViewModel();

            viewModel.IdEspecialidad = Idespecialidad;
            viewModel.CargarDatos(Contexto);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RolAuthFilter(ConstanHelpers.Rol.Administrador)]
        public ActionResult AddEdit(EspecialidadAddEditViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    viewModel.IdEspecialidad = viewModel.IdEspecialidad;
                    viewModel.CargarDatos(Contexto);

                    TryUpdateModel(viewModel);

                    TempData["MensajeAddEditEspecialidad"] = "Por favor, complete los campos requeridos.";
                    return View(viewModel);
                }

                Especialidades objEspecialidad = null;

                if (viewModel.IdEspecialidad.HasValue)
                {
                    objEspecialidad = Contexto.Especialidades.Find(viewModel.IdEspecialidad);
                }
                else
                {
                    objEspecialidad =  new Especialidades();
                    objEspecialidad.Nombre = viewModel.Nombre;
                    objEspecialidad.Descripcion = viewModel.Descripcion;
                    //objEspecialidad.Fecha = DateTime.Now;
                    //objEspecialidad.Telefono = viewModel.Telefono;
                    //objEspecialidad.IdEspecialidad = viewModel.Especialidades;
                    //objEspecialidad.IdUsuario = Session.GetUsuarioId();


                    Contexto.Especialidades.Add(objEspecialidad);
                }

                objEspecialidad.Nombre = viewModel.Nombre;
                objEspecialidad.Descripcion = viewModel.Descripcion;
                //objEspecialidad.Fecha = DateTime.Now;
                //objEspecialidad.Telefono = viewModel.Telefono;
                //objEspecialidad.IdEspecialidad = viewModel.Especialidades;
                //objEspecialidad.IdUsuario = Session.GetUsuarioId();
                
                Contexto.SaveChanges();
                TempData["MensajeEspecialidad"] = "La consulta fue procesada exitosamente.";
            }
            catch (Exception ex)
            {
                viewModel.IdEspecialidad = viewModel.IdEspecialidad;
                //viewModel.CargarDatos(Contexto);

                TryUpdateModel(viewModel);

                TempData["MensajeAddEditEspecialidad"] = "Hubo un error, consulte con el administrador.";
                return View(viewModel);
            }

            return RedirectToAction("Index");
        }
    }
}

CIP.Web/Controllers/PostulanteController.cs
using CIP.Models.Contexto;
using CIP.Models.Helpers;
using CIP.Web.Filters;
using CIP.Web.Helpers;
using CIP.Web.Models.Postulante;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CIP.Web.Controllers
{
    public class PostulanteController : BaseController
    {
        [RolAuthFilter(ConstanHelpers.Rol.Administrador,ConstanHelpers.Rol.Recepcionista)]
        public ActionResult Index()
        {
            var viewModel = new PostulanteIndexViewModel();

            var lista =  Contexto.Postulantes.ToList();
                //.Where(x => x.TipoPreguntaId == ConstanHelpers.TipoPregunta.PreguntaFrecuente)
                //.ToList(); 

            viewModel.ListPreguntas = lista;

            return View(viewModel);
        }

        [RolAuthFilter(ConstanHelpers.Rol.Administrador, ConstanHelpers.Rol.Recepcionista)]
        public ActionResult Detail(int Idpostulante)
        {
            var viewModel = new PostulanteDetailViewModel();

            viewModel.IdPostulante = Idpostulante;
            // llave primaria de una columna
            viewModel.PostulantesDetail = Contexto.Postulantes.Find(Idpostulante);

            // llave primaria compleja de mas de una columna
            //Contexto.ConsultaLegal.FirstOrDefault(x => x.ConsultaLegalId == 10 &&
            //        x.Estado == "XYZ" && x.TemaId == 9);

            return View(viewModel);
        }

        [RolAuthFilter(ConstanHelpers.Rol.Administrador)]
        public ActionResult Delete(int Idpostulante)
        {
            try
            {
                var objPostulante = Contexto.Postulantes
                    .FirstOrDefault(x => x.IdPostulante == Idpostulante);// &&
                       // x.TipoPreguntaId == ConstantHelpers.TipoPregunta.PreguntaFrecuente);

                if (objPostulante == null)
                {
                    TempData["MensajePostulante"] = "El registro no existe en BD.";
                    return RedirectToAction("Index");
                }

                Contexto.Postulantes.Remove(objPostulante);
                Contexto.SaveChanges();
                TempData["MensajePostulante"] = "El registro fue eliminado exitosamente.";
            }
            catch (Exception ex)
            {
                TempData["MensajePostulante"] = "Ocurrio un error, contacte con el administrador";
            }

            return RedirectToAction("Index");
        }

        [RolAuthFilter(ConstanHelpers.Rol.Administrador, ConstanHelpers.Rol.Recepcionista))]
        public ActionResult AddEdit(int? Idpostulante)
        {
            var viewModel = new PostulanteAddEditViewModel();

            viewModel.IdPostulante = Idpostulante;
            viewModel.CargarDatos(Contexto);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RolAuthFilter(ConstanHelpers.Rol.Administrador, ConstanHelpers.Rol.Recepcionista))]
        public ActionResult AddEdit(PostulanteAddEditViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    viewModel.IdPostulante = viewModel.IdPostulante;
                    viewModel.CargarDatos(Contexto);

                    TryUpdateModel(viewModel);

                    TempData["MensajeAddEditPostulante"] = "Por favor, complete los campos requeridos.";
                    return View(viewModel);
                }

                Postulantes objPostulante = null;

                if (viewModel.IdPostulante.HasValue)
                {
                    objPostulante = Contexto.Postulantes.Find(viewModel.IdPostulante);
                }
                else
                {
                    objPostulante = new Postulantes();
                    objPostulante.DatosPostulante = viewModel.DatosPostulante ;
                    objPostulante.DNI = viewModel.DNI;
                    objPostulante.Fecha = DateTime.Now;
                    objPostulante.Telefono = viewModel.Telefono;
                    objPostulante.IdEspecialidad = viewModel.Especialidades;
                    objPostulante.IdUsuario = Session.GetUsuarioId();
                    

                    Contexto.Postulantes.Add(objPostulante);
                }

                objPostulante.DatosPostulante = viewModel.DatosPostulante;
                objPostulante.DNI = viewModel.DNI;
                objPostulante.Fecha = DateTime.Now;
                objPostulante.Telefono = viewModel.Telefono;
                objPostulante.IdEspecialidad = viewModel.Especialidades;
                objPostulante.IdUsuario = Session.GetUsuarioId();

                Contexto.SaveChanges();
                TempData["MensajePostulante"] = "La consulta fue procesada exitosamente.";
            }
            catch (Exception ex)
            {
                viewModel.IdPostulante = viewModel.IdPostulante;
                viewModel.CargarDatos(Contexto);

                TryUpdateModel(viewModel);

                TempData["MensajeAddEditPostulante"] = "Hubo un error, consulte con el administrador.";
                return View(viewModel);
            }

            return RedirectToAction("Index");
        }
    }
}

CIP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="@Url.Content("~/Content/Template/css/bootstrap.css")" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="@Url.Content("~/Content/Template/css/font-awesome.css")" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="@Url.Content("~/Content/Template/css/custom.css")" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Binary admin</a>
            </div>
            <div style="color: white; padding: 15px 50px 5px 50px; float: right; font-size: 16px;">
                <a href="@Url.Action("Logout", "Auth")" class="btn btn-danger btn-lg square-btn-adjust">
                    <i class="fa fa-sign-out"></i> Cerrar Sesión
                </a>
            </div>
        </nav>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">


                <ul class="nav" id="main-menu">
                    <li class="text-center">
                        <img src="@Url.Content("~/Content/Template/img/find_user.png")" class="user-image img-responsive" />
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "Especialidad")"><i class="fa fa-dashboard fa-3x"></i> Especialidades</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Postulante")"><i class="fa fa-edit fa-3x"></i> Postulantes</a>
                    </li>

                </ul>


            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">


                @RenderBody()


            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="@Url.Content("~/Content/Template/js/jquery-1.10.2.js")"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="@Url.Content("~/Content/Template/js/bootstrap.min.js")"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="@Url.Content("~/Content/Template/js/jquery.metisMenu.js")"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="@Url.Content("~/Content/Template/js/custom.js")"></script>
</body>
</html>